services:
  - type: web
    name: hackathon-mirakl-webapp
    runtime: node
    plan: starter
    region: frankfurt
    rootDir: webapp
    buildCommand: npm install && npm run build
    startCommand: npm run render:start
    healthCheckPath: /api/kpi
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        value: file:/var/data/dev.db
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
